name: master to live
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SERVER_PASSWORD: ${{ secrets.DEVELOP_SERVER_PASSWORD }}
  SERVER_USERNAME: ${{ secrets.DEVELOP_SERVER_USERNAME }}
  SERVER_HOST: ${{ secrets.DEVELOP_SERVER_HOST }}
  SERVER_PATH: ${{ secrets.DEVELOP_SERVER_PATH }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the master container
      run: |
       sshpass -p 'YFTt9ws=sx9V4>%"' rsync -av ../.././ 'ssh -o StrictHostKeyChecking=no -p 22 root@103.98.32.62:~/home/admin/web/gittest.pmhere.xyz/public_html/'