name: master to live
on:
  push:
    branches:
      - master

env:
  SERVER_PASSWORD: ${{ secrets.DEVELOP_SERVER_PASSWORD }}
  SERVER_USERNAME: ${{ secrets.DEVELOP_SERVER_USERNAME }}
  SERVER_HOST: ${{ secrets.DEVELOP_SERVER_HOST }}
  SERVER_PATH: ${{ secrets.DEVELOP_SERVER_PATH }}

jobs:
  Staging-deploy:
    name: Staging-deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependency and Deploy on Staging Server
      if: github.ref == 'refs/heads/master'
      run: |
        mkdir test
